version: '2'
services:
  httpd:
    image: httpd:2.4.27-alpine
    container_name: dncngrl-static-httpd
    ports:
      - 8083:80
    restart: always
    tty: false
    env_file: .env
    volumes_from:
      - sftp
    volumes:
      - ./setting/apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    networks:
      - front
      - back-dncngrl-static

  sftp:
    image: atmoz/sftp:alpine
    container_name: dncngrl-static-sftp
    ports:
      - '2222:22'
    volumes_from:
      - data
    command: ryo::1001:100:htdocs
    networks:
      - back-dncngrl-static

  data:
    image: busybox:1.27.1-musl
    container_name: dncngrl-static-data
    volumes:
      - dncngrl-static-data:/home/ryo
      - ./ssh/dncngrl_static_rsa.pub:/home/ryo/.ssh/keys/dncngrl_static_rsa.pub:ro
      - ./backup:/backup
    networks:
      - back-dncngrl-static

volumes:
  dncngrl-static-data:
    external: true

networks:
  front:
    external: true
  back-dncngrl-static:
    external: true
