version: '2'
services:
  httpd:
    image: httpd:2.4.27-alpine
    container_name: ${CONTAINER_NAME_PREFIX}-static-httpd
    ports:
      - ${VIRTUAL_PORT}:80
    restart: always
    tty: false
    env_file: .env
    volumes_from:
      - sftp
    volumes:
      - ./setting/apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./setting/apache2/conf.d/my_setting.conf:/usr/local/apache2/conf.d/my_setting.conf:ro
    networks:
      - front
      - back-static

  sftp:
    image: atmoz/sftp:alpine
    container_name: ${CONTAINER_NAME_PREFIX}-static-sftp
    ports:
      - '${SFTP_PORT}:22'
    volumes_from:
      - data
    command: ${SFTP_USER_NAME}::1001:100:htdocs
    networks:
      - back-static

  data:
    image: busybox:1.27.1-musl
    container_name: ${CONTAINER_NAME_PREFIX}-static-data
    volumes:
      - static-data:/home/${SFTP_USER_NAME}
      - ./ssh/${SFTP_PUBLIC_KEY_NAME}:/home/${SFTP_USER_NAME}/.ssh/keys/${SFTP_PUBLIC_KEY_NAME}:ro
      - ./backup:/backup
    networks:
      - back-static

volumes:
  static-data:
    external: true

networks:
  front:
    external: true
  back-static:
    external: true
